### ISSUE TITLE
Code Review - John Brock

### ISSUE THREAD

**Issue by jgbrock178** [vinny11123/CMP1903M-Assessment-1-Base-Code#2]
### Code Style
Most of these are nitpicking about how the code is written, especially if it hinders readability. However, none of these will impact the running of the code.
- [x] 👍 Good use of encapsulation
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Input.cs#L15
- [x] (nitpick) You could use `\n\n` instead of having the empty line here.
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L69-L73

### Documentation / Comments
Any suggestions related to your comments and documentation in the code.
- [x] Old code should be removed from comments like this. Git will retain the history for anything committed.
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L43
- [x] (nitpicking) There are mixed comment styles - for readability I recommend `// comment here` instead of `//comment here`. Main issue however is consistency across the code. To be fair, looks like your comments follow this, but ideally clean up the templated ones as well.
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L49
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L44

### User Experience
This section gives suggestions for anything that could improve the UX of the users running your code.
- [x] 👍 Nice and friendly text used when interacting with the user.
- [x] This would work better as a numbered input, similar to the example below it.
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Input.cs#L42
https://github.com/vinny11123/CMP1903M-Assessment-1-Base-Code/blob/07092753eab90ceec236a9069eaed1da85e30019/CMP1903M%20Assessment%201%20Base%20Code/Program.cs#L69-L73

### Error / Exception Handling
Any recommendations or issues relating to error checking and handling.
- [x] 👍 User input verified and exceptions and try/catch blocks used for possible exceptions when executed.

### General Feedback
- [x] Add a .gitignore so non-needed files (e.g. builds and user configs) aren't included. You can google for generic Visual Studio gitignores and include these.

**Comment by vinny11123** [comment]
Thank your for the helpful feedback John 👍
